src/objects/Car__c.object
<CustomObject>
    <fields>
        <fullName>CarCountry__c</fullName>
        <label>Car Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>South Korea</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>England</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Value1</fullName>
                    <isActive>false</isActive>
                    <label>Value1</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CarTypeId__c</fullName>
        <formula>RelatedCarType__r.CarTypeId__c</formula>
        <label>Car Type Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Car_License__c</fullName>
        <externalId>true</externalId>
        <label>Car License</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RelatedCarType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Car Type</label>
        <referenceTo>CarType__c</referenceTo>
        <relationshipLabel>Cars</relationshipLabel>
        <relationshipName>Cars</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Car</label>
    <nameField>
        <label>Car</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CarSale__c.object
<CustomObject>
    <fields>
        <fullName>CarBrand__c</fullName>
        <formula>TEXT(RelatedCar__r.RelatedCarType__r.CarBrand__c)</formula>
        <label>Car Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarTypeId__c</fullName>
        <formula>RelatedCar__r.CarTypeId__c</formula>
        <label>Car Type Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <formula>RelatedCar__r.RelatedCarType__r.Model__c</formula>
        <label>Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RelatedCar__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Car</label>
        <referenceTo>Car__c</referenceTo>
        <relationshipLabel>Car Sales</relationshipLabel>
        <relationshipName>Car_Sales</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Car Sale</label>
    <nameField>
        <label>Car Sale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CarType__c.object
<CustomObject>
    <fields>
        <fullName>BodyStyle__c</fullName>
        <label>Body Style</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Convertible</fullName>
                </value>
                <value>
                    <fullName>Coupe</fullName>
                </value>
                <value>
                    <fullName>Hatchback</fullName>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
                <value>
                    <fullName>SUV</fullName>
                </value>
                <value>
                    <fullName>Sedan</fullName>
                </value>
                <value>
                    <fullName>Van/Minivan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CarBrand__c</fullName>
        <label>Car Brand</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acura</fullName>
                </value>
                <value>
                    <fullName>Alfa Romeo</fullName>
                </value>
                <value>
                    <fullName>Audi</fullName>
                </value>
                <value>
                    <fullName>BMW</fullName>
                </value>
                <value>
                    <fullName>Chevrolet</fullName>
                </value>
                <value>
                    <fullName>Chrysler</fullName>
                </value>
                <value>
                    <fullName>FIAT</fullName>
                </value>
                <value>
                    <fullName>Ford</fullName>
                </value>
                <value>
                    <fullName>Honda</fullName>
                </value>
                <value>
                    <fullName>Hyundai</fullName>
                </value>
                <value>
                    <fullName>Jeep</fullName>
                </value>
                <value>
                    <fullName>Kia</fullName>
                </value>
                <value>
                    <fullName>Land Rover</fullName>
                </value>
                <value>
                    <fullName>MAZDA</fullName>
                </value>
                <value>
                    <fullName>Mercedes-Benz</fullName>
                </value>
                <value>
                    <fullName>Mitsubishi</fullName>
                </value>
                <value>
                    <fullName>Nissan</fullName>
                </value>
                <value>
                    <fullName>Subaru</fullName>
                </value>
                <value>
                    <fullName>Tesla</fullName>
                </value>
                <value>
                    <fullName>Toyota</fullName>
                </value>
                <value>
                    <fullName>Volkswagen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CarTypeId__c</fullName>
        <externalId>true</externalId>
        <label>Car Type Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Car Type</label>
    <nameField>
        <label>Car Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CarDealershipService.cls
/**
 * Created by Dante on 06/07/2022.
 */

public with sharing class CarDealershipService {

    @AuraEnabled
    public static CarTypesResponse getCarTypes() {
        CarTypesResponse response = new CarTypesResponse();
        List<CarType__c> carTypes = [
                SELECT Id, CarTypeId__c, Model__c, CarBrand__c, BodyStyle__c
                FROM CarType__c
                ORDER BY CarBrand__c, Model__c
        ];
        for (CarType__c carType : carTypes) {
            CarType obj = new CarType();
            obj.carTypeSFId = carType.Id;
            obj.carTypeId = Integer.valueOf(carType.CarTypeId__c);
            obj.model = carType.Model__c;
            obj.brand = carType.CarBrand__c;
            obj.bodyStyle = carType.BodyStyle__c;
            response.carTypes.add(obj);
        }
        System.debug('response: ' + JSON.serializePretty(response));
        return response;
    }
    @AuraEnabled
    public static DetailsResponse getInfoByCarType(String carTypeSFId) {
        DetailsResponse response = new DetailsResponse();
        List<CarSale__c> carSales = [
                SELECT Id, Price__c, Date__c, RelatedCar__r.Car_License__c,
                        RelatedCar__r.RelatedCarType__r.CarTypeId__c,
                        RelatedCar__r.RelatedCarType__r.Model__c,
                        RelatedCar__r.RelatedCarType__r.CarBrand__c,
                        RelatedCar__r.RelatedCarType__r.BodyStyle__c,
                        RelatedCar__r.CarCountry__c
                FROM CarSale__c
                WHERE RelatedCar__r.RelatedCarType__c = :carTypeSFId
                AND Date__c = N_YEARS_AGO:3 // The records point to 2019..
                ORDER BY Date__c
        ];
        Decimal totalAmtRaised = 0;
        Date mostExpSaleDate;
        Decimal mostExpSaleDateAmount = 0;
        String mostExpLicensePlate;
        Decimal mostExpLicensePlateAmount = 0;
        Map<Date, Decimal> AmountPerDate = new Map<Date, Decimal>();
        for(CarSale__c carSale : carSales){
            if(response.carType.carTypeSFId==null){
                response.carType.carTypeSFId = carSale.RelatedCar__r.RelatedCarType__r.Id;
                response.carType.carTypeId = Integer.valueOf(carSale.RelatedCar__r.RelatedCarType__r.CarTypeId__c);
                response.carType.model = carSale.RelatedCar__r.RelatedCarType__r.Model__c;
                response.carType.brand = carSale.RelatedCar__r.RelatedCarType__r.CarBrand__c;
                response.carType.bodyStyle = carSale.RelatedCar__r.RelatedCarType__r.BodyStyle__c;
            }
            totalAmtRaised+=carSale.Price__c;
            if(carSale.Price__c>mostExpLicensePlateAmount){
                mostExpLicensePlate = carSale.RelatedCar__r.Car_License__c;
                mostExpLicensePlateAmount = carSale.Price__c;
            }
            Decimal dayAmount = carSale.Price__c;
            if(AmountPerDate.containsKey(carSale.Date__c)){
                dayAmount += AmountPerDate.get(carSale.Date__c);
            }
            AmountPerDate.put(carSale.Date__c, dayAmount);
        }
        for(Date dateAux : AmountPerDate.keySet()){
            if(AmountPerDate.get(dateAux)>mostExpSaleDateAmount){
                mostExpSaleDate = dateAux;
                mostExpSaleDateAmount = AmountPerDate.get(dateAux);
            }
        }
        // In case there are no sales we still have to display some data
        if(carSales.isEmpty()){
            CarType__c carType = [
                    SELECT Id, CarTypeId__c, Model__c, CarBrand__c, BodyStyle__c
                    FROM CarType__c
                    WHERE Id =:carTypeSFId
            ];
            response.carType.carTypeSFId = carType.Id;
            response.carType.carTypeId = Integer.valueOf(carType.CarTypeId__c);
            response.carType.model = carType.Model__c;
            response.carType.brand = carType.CarBrand__c;
            response.carType.bodyStyle = carType.BodyStyle__c;
        }
        response.details.totalQttSold = carSales.size();
        response.details.totalAmtRaised = totalAmtRaised;
        response.details.mostExpSaleDate = mostExpSaleDate;
        response.details.mostExpLicensePlate = mostExpLicensePlate;
        response.details.mostExpSalePrice = mostExpLicensePlateAmount;
        return response;
    }
    public class CarTypesResponse {
        @AuraEnabled public List<CarType> carTypes = new List<CarType>();
    }
    public class CarType {
        @AuraEnabled public Id carTypeSFId { get; set; }
        @AuraEnabled public Integer carTypeId { get; set; }
        @AuraEnabled public String model { get; set; }
        @AuraEnabled public String brand { get; set; }
        @AuraEnabled public String bodyStyle { get; set; }
    }
    public class DetailsResponse {
        @AuraEnabled public Details details = new Details();
        @AuraEnabled public CarType carType = new CarType();
    }
    public class Details {
        @AuraEnabled public Integer totalQttSold { get; set; } // Total Quantity sold value
        @AuraEnabled public Decimal totalAmtRaised { get; set; }  // Total Money Raised value
        @AuraEnabled public Date mostExpSaleDate { get; set; }  // Most expensive sale date during the period
        @AuraEnabled public String mostExpLicensePlate { get; set; }  // Most expensive Car license plate during the period
        @AuraEnabled public Decimal mostExpSalePrice { get; set; }  // Most expensive sale price during the period
    }
}